# Generated by Django 5.2.16 on 2026-07-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(db_index=True, help_text='The name shown to other users inside the chat. Must be unique.', max_length=50, unique=True),
        ),
    ]
